services:

  - type: web
    name: rag-backend
    runtime: docker
    dockerfilePath: ./Dockerfile.backend
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: rag-frontend
    runtime: docker
    dockerfilePath: ./Dockerfile.frontend
    plan: free
    envVars:
      - key: BACKEND_URL
        fromService:
          name: rag-backend
          type: web
          property: host
    autoDeploy: true
